#   +---------------+
#   | RLMTownNoMobs |
#   |               |
#   | Configuration |
#   +---------------+


# List of banned mobs
bannedMobs:
  - BAT
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - ENDER_DRAGON
  - ENDERMAN
  - GHAST
  - GIANT
  - MAGMA_CUBE
  - PIG_ZOMBIE
  - SILVERFISH
  - SKELETON
  - SLIME
  - SPIDER
  - WITCH
  - WITHER
  - ZOMBIE

# Percentage of mobs to be converted to villagers
# Default: 0.05 (5%)
villagerRatio: 0.05

# Whether villagers can use doors in towns
# Default: false
villagerDoors: false